<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNyojAnE\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNyojAnE/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNyojAnE.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNyojAnE\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNyojAnE\App_KernelDevDebugContainer([
    'container.build_hash' => 'NyojAnE',
    'container.build_id' => '993e1ceb',
    'container.build_time' => 1678699377,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNyojAnE');
